name: stack

on:
  push:
  pull_request:

jobs:
  build:
    name: ghc ${{ matrix.ghc }} - ${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10.3.0"]
        ghc:
          - "9.2.8"
          - "9.4.7"
          - "9.6.3"
        include:
          - repo: "hackage"
          - ghc: "9.8.1"
            repo: "github"
          - ghc: "9.8.1"
            repo: "hackage"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup z3
        uses: pavpanchekha/setup-z3@1.2.2
        with:
          version: "4.8.7"

      - name: Setup Stack
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: true
          stack-version: "latest"

      - name: Configure the build
        run: |
          if [ ${{ matrix.repo }} == "hackage" ]
          then
            sed "s/\.\././g" ./stack/stack-${{ matrix.ghc }}.yaml > stack.yaml
          fi
          # generate stack.yaml.lock
          stack build --no-terminal --dry-run

      - name: Cache ~/.stack and .stack-work
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('**/*.cabal', './stack.yaml', './stack.yaml.lock') }}

      - name: Build
        run: stack build --no-terminal
